# Generated by Django 3.2.7 on 2021-10-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_and_school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('password', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(default='', upload_to='Userimages/schoolimages')),
                ('clusterIds', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
